name: Build Java

on:
  workflow_call:

jobs:
  reusable_workflow_build:
    name: Reusable
    runs-on: rss-primary
    env:
      PRJ_FULL_PATH: ${{ github.workspace }}/base-code
      ADM_FULL_PATH: ${{ github.workspace }}/devsecops-code
    steps:
      - name: Get Composite
        uses: actions/checkout@v4
        with:
          repository: devsecops-lab-ciandt/devsecops-workflows
          ref: main
          path: ${{ env.ADM_FULL_PATH }}

      - name: Run Composite
        uses: ./devsecops-code/actions/setup-java
        with:
          jdk_version: '17'

      - name: Maven Build
        run: |
          mvn -B -DskipTests clean package
          ls -l
        working-directory: ${{ env.PRJ_FULL_PATH }}

      - uses: actions/upload-artifact@v4
        name: Upload Artifacts
        with:
          name: package
          path: ${{ env.PRJ_FULL_PATH }}/target
          retention-days: 1
