name: Build Node

on:
  workflow_call:

jobs:
  reusable_workflow_build:
    name: Reusable
    runs-on: ${{ inputs.runner_scale_set }}
    container:
      image: node:lts-buster-slim
    env:
      PRJ_FULL_PATH: ${{ github.workspace }}/base-code
      ADM_FULL_PATH: ${{ github.workspace }}/devsecops-code
    steps:
      - name: Get Composite
        uses: actions/checkout@v4
        with:
          repository: devsecops-lab-ciandt/devsecops-workflows
          ref: main
          path: ${{ env.ADM_FULL_PATH }}

      - name: Run Composite
        uses: ./devsecops-code/actions/setup-node
        with:
          node_version: '18'

      - name: NPM Install
        run: |
          npm ci
          ls -l
        working-directory: ${{ env.PRJ_FULL_PATH }}

      - name: NPM Build
        run: |
          npm run build
          ls -l
        working-directory: ${{ env.PRJ_FULL_PATH }}

      - uses: actions/upload-artifact@v4
        name: Upload Artifacts
        with:
          name: package
          path: ${{ env.PRJ_FULL_PATH }}/build
          retention-days: 1
