name: Test Java

on:
  workflow_call:

jobs:
  reusable_workflow_test:
    name: Reusable
    runs-on: ubuntu-24.04
    container:
      image: maven:3.9.2
    env:
      PRJ_FULL_PATH: ${{ github.workspace }}/base-code
      ADM_FULL_PATH: ${{ github.workspace }}/devsecops-code
    steps:
      - name: Get Composite
        uses: actions/checkout@v4
        with:
          repository: devsecops-lab-ciandt/devsecops-workflows
          ref: main
          path: ${{ env.ADM_FULL_PATH }}

      - name: Run Composite
        uses: ./devsecops-code/actions/setup-java
        with:
          jdk_version: '17'

      - name: Unit Test
        run: |
          mvn -B clean test
          ls -l
        working-directory: ${{ env.PRJ_FULL_PATH }}

      - uses: actions/upload-artifact@v4
        name: Upload Artifacts
        with:
          name: report
          path: ${{ env.PRJ_FULL_PATH }}/target/surefire-reports/*.xml
          retention-days: 1
